#pragma once

// From glfw3.h
#define TS_MOUSE_BUTTON_1 0
#define TS_MOUSE_BUTTON_2 1
#define TS_MOUSE_BUTTON_3 2
#define TS_MOUSE_BUTTON_4 3
#define TS_MOUSE_BUTTON_5 4
#define TS_MOUSE_BUTTON_6 5
#define TS_MOUSE_BUTTON_7 6
#define TS_MOUSE_BUTTON_8 7
#define TS_MOUSE_BUTTON_LAST TS_MOUSE_BUTTON_8
#define TS_MOUSE_BUTTON_LEFT TS_MOUSE_BUTTON_1
#define TS_MOUSE_BUTTON_RIGHT TS_MOUSE_BUTTON_2
#define TS_MOUSE_BUTTON_MIDDLE TS_MOUSE_BUTTON_3